/*
 * @Description: In User Settings Edit
 * @Author: your name
 * @Date: 2019-10-10 20:22:48
 * @LastEditTime: 2019-10-10 20:22:48
 * @LastEditors: your name
 */
export const ACTION_SET_FROM = 'SET_FROM';
export const ACTION_SET_TO =  'SET_TO';
export const ACTION_SET_IS_CITY_SELECTORVISIBLE = 'SET_IS_CITY_SELECTORVISIBLE ';
export const ACTION_SET_CURRENNT_SELECTING_LEFT_CITY = 'SET_CURRENNT_SELECTING_LEFT_CITY';
export const ACTION_SET_CITY_DATA = 'SET_CITY_DATA';
export const ACTION_SET_IS_LOADING_CITY_DATA =  'SET_IS_LOADING_CITY_DATA'; 
export const ACTION_SET_IS_DATE_SELECTOR_VISIBLE = 'SET_IS_DATE_SELECTOR_VISIBLE';
export const ACTION_SET_HIGH_SPEED = 'SET_HIGH_SPEED';